[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "K8s"
authors = [{name = "harrkout", email = "harrkout@gmail.com"}]
dynamic = ["version", "description"]
